<a href="https://colab.research.google.com/github/iecgerman/python-numpy-pandas/blob/master/clase10.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# Cálculos Matriciales en NumPy

import numpy as np

A = np.array([[1,2],[3,4]])
B = np.array([[5,6],[7,8]])

# SUMA DE MATRICES

sum = A + B
print(A)
print(B)
print(sum)

[[1 2]
 [3 4]]
[[5 6]
 [7 8]]
[[ 6  8]
 [10 12]]


In [ ]:
# Multiplicación

product = np.dot(A,B)
print(product)

[[19 22]
 [43 50]]


In [ ]:
mult = A * B
print(A)
print(B)
print(mult)

# creo que no es lo mismo que dot

[[1 2]
 [3 4]]
[[5 6]
 [7 8]]
[[ 5 12]
 [21 32]]


In [ ]:
A = np.array([[1,2],[3,4]])
print(A)

det_A = np.linalg.det(A)
print(det_A)

inv_A = np.linalg.inv(A)
print(inv_A)

[[1 2]
 [3 4]]
-2.0000000000000004
[[-2.   1. ]
 [ 1.5 -0.5]]


In [ ]:
# Resolver Ax = b

b = np.array([9,11])
x = np.linalg.solve(A,b)
print(x)

[-7.  8.]
