<a href="https://colab.research.google.com/github/iecgerman/python-numpy-pandas/blob/master/clase02.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
!pip install numpy pandas

In [ ]:
import numpy as np
escalar = np.array(42)
print (type(escalar))
print(escalar)

<class 'numpy.ndarray'>
42


In [ ]:
vector = np.array([30,29,42,35,31,33,36,42])
print(vector)

[30 29 42 35 31 33 36 42]


In [ ]:
matrix = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(matrix)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [ ]:
tensor = np.array([[[1,2],[3,4],[5,6],[7,8]]])
print(tensor)

[[[1 2]
  [3 4]
  [5 6]
  [7 8]]]


In [ ]:
array_arange =  np.arange(10)
print(array_arange)

[0 1 2 3 4 5 6 7 8 9]


In [ ]:
eye_matrix = np.eye(6)
print(eye_matrix)

[[1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 1.]]


In [ ]:
diag = np.diag([1,2,3,4,5,6,7])
print(diag)

[[1 0 0 0 0 0 0]
 [0 2 0 0 0 0 0]
 [0 0 3 0 0 0 0]
 [0 0 0 4 0 0 0]
 [0 0 0 0 5 0 0]
 [0 0 0 0 0 6 0]
 [0 0 0 0 0 0 7]]


In [ ]:
random =  np.random.random((2,3))
print(random)

[[0.30666714 0.91079815 0.76189985]
 [0.1764467  0.12179611 0.74883962]]
