<a href="https://colab.research.google.com/github/iecgerman/python-numpy-pandas/blob/master/clase08.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
# Transformación de Arrays: Reshape y Manipulación

import numpy as np

# TRANSPOSE

matrix = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(matrix)

transposed_matrix = matrix.T
print(transposed_matrix)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 4 7]
 [2 5 8]
 [3 6 9]]


In [5]:
# RESHAPE

array = np.arange(1,13)
print(array)

reshaped_array = array.reshape(3,4)
print(reshaped_array)

[ 1  2  3  4  5  6  7  8  9 10 11 12]
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [7]:
# REVERSE

reversed_array = array[::-1]
print(array)
print(reversed_array)

[ 1  2  3  4  5  6  7  8  9 10 11 12]
[12 11 10  9  8  7  6  5  4  3  2  1]


In [16]:
# FLATTENING

matrix = np.array([[1,2,3],[4,5,6],[7,8,9]])

flattened_array = matrix.flatten()
print(matrix)
print(flattened_array)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[1 2 3 4 5 6 7 8 9]
