<a href="https://colab.research.google.com/github/iecgerman/python-numpy-pandas/blob/master/clase04.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# Introducción al álgebra lineal con NumPy

Ejemplos aplicativos

Gráficos por Computadora: Las transformaciones lineales se utilizan para rotar, escalar y traducir objetos en la pantalla.

Procesamiento de Imágenes: Las matrices de convolución (kernels) se usan para aplicar filtros a las imágenes, mejorando su calidad o destacando características específicas.

Aprendizaje Automático: Los algoritmos de regresión lineal, redes neuronales y otros modelos dependen en gran medida de las operaciones matriciales.

In [1]:
# Suma de matrices

import numpy as np

A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])

suma = A + B
print("Suma de matrices:\n", suma)

Suma de matrices:
 [[ 6  8]
 [10 12]]


In [2]:
# Multiplicación de matrices

producto = np.dot(A, B)
print("Producto de matrices:\n", producto)

Producto de matrices:
 [[19 22]
 [43 50]]


In [3]:
# Determinante de una matriz

determinante = np.linalg.det(A)
print("Determinante de A:", determinante)

Determinante de A: -2.0000000000000004


In [4]:
# Inversa de una matriz

inversa = np.linalg.inv(A)
print("Inversa de A:\n", inversa)

Inversa de A:
 [[-2.   1. ]
 [ 1.5 -0.5]]


In [5]:
# Valores y vectores propios

valores_propios, vectores_propios = np.linalg.eig(A)
print("Valores propios de A:\n", valores_propios)
print("Vectores propios de A:\n", vectores_propios)

Valores propios de A:
 [-0.37228132  5.37228132]
Vectores propios de A:
 [[-0.82456484 -0.41597356]
 [ 0.56576746 -0.90937671]]


In [6]:
# Resolución de sistemas de ecuaciones lineales

B = np.array([1, 2])
X = np.linalg.solve(A, B)
print("Solución del sistema AX = B:\n", X)

Solución del sistema AX = B:
 [0.  0.5]
