<a href="https://colab.research.google.com/github/iecgerman/python-numpy-pandas/blob/master/clase07.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# Elementos Únicos y sus Conteos: Copias y Vistas

import numpy as np

survey_responses = np.array(["bueno", "excelente", "malo",
                             "bueno", "malo", "excelente",
                             "bueno", "bueno", "malo",
                             "excelente", "excelente", "excelente"])

print(np.unique(survey_responses))

['bueno' 'excelente' 'malo']


In [ ]:
# Elementos Únicos y sus Conteos: Copias y Vistas

import numpy as np

survey_responses = np.array(["bueno", "excelente", "malo",
                             "bueno", "malo", "excelente",
                             "bueno", "bueno", "malo",
                             "excelente", "excelente", "excelente"])

print(np.unique(survey_responses))

['bueno' 'excelente' 'malo']


In [11]:
# Elementos Únicos y sus Conteos: Copias y Vistas

import numpy as np

survey_responses = np.array(["bueno", "excelente", "malo",
                             "bueno", "malo", "excelente",
                             "bueno", "bueno", "malo",
                             "excelente", "excelente", "excelente"])

print(np.unique(survey_responses))

['bueno' 'excelente' 'malo']


In [12]:
unique_elements, counts = np.unique(survey_responses, return_counts=True)
print(unique_elements)
print(counts)

['bueno' 'excelente' 'malo']
[4 5 3]


Elementos Únicos y Conteos:

Utiliza **np.unique** para encontrar elementos únicos y sus conteos en arrays unidimensionales y multidimensionales.

In [15]:
# Ejemplo con ejercicio de clase 6 de Broadcasting

prices = np.random.randint(1, 99, size=(10,10))
print(prices)

unique_elements_in_prices, counts = np.unique(prices, return_counts=True)
print(unique_elements_in_prices)
print(counts)

[[86 98 61  8 28 74 92 83 17  6]
 [43 40 61 23 46 39 77 95 69 60]
 [77 89 30 49 16 82 24 96 88 20]
 [79 27  5 17 24 19  6 90 26 14]
 [48 90 62 37  1 82 81 17  4 18]
 [21 83 40  5 47 47  4  7 44 70]
 [62 41 61 94 85 59 87 57 74 79]
 [68 60  3 90 50 45 93 73 60  4]
 [60 83  6 50 45 76 97 51 48 58]
 [ 8 69 49 27  5 25 17 38 56 12]]
[ 1  3  4  5  6  7  8 12 14 16 17 18 19 20 21 23 24 25 26 27 28 30 37 38
 39 40 41 43 44 45 46 47 48 49 50 51 56 57 58 59 60 61 62 68 69 70 73 74
 76 77 79 81 82 83 85 86 87 88 89 90 92 93 94 95 96 97 98]
[1 1 3 3 3 1 2 1 1 1 4 1 1 1 1 1 2 1 1 2 1 1 1 1 1 2 1 1 1 2 1 2 2 2 2 1 1
 1 1 1 4 3 2 1 2 1 1 2 1 2 2 1 2 3 1 1 1 1 1 3 1 1 1 1 1 1 1]


In [19]:
# VISTAS

array_x = np.arange(10)
print(array_x)
view_y = array_x[1:3]
print(view_y)

array_x[1:3] = [10,11]
print(array_x)
print(view_y)

[0 1 2 3 4 5 6 7 8 9]
[1 2]
[ 0 10 11  3  4  5  6  7  8  9]
[10 11]


In [23]:
# COPIAS

array_x = np.arange(10)
copy_x = array_x[[1,2]]
print(array_x)
print(copy_x)
array_x[1:3] = [10,11]
print(array_x)
print(copy_x)

[0 1 2 3 4 5 6 7 8 9]
[1 2]
[ 0 10 11  3  4  5  6  7  8  9]
[1 2]


Copias y Vistas:

Las **vistas** son referencias al mismo bloque de memoria que el array original, mientras que las **copias** son réplicas independientes. Cambios en una vista afectan al array original, pero cambios en una copia no.

Las **vistas** comparten la memoria con el array original y las modificaciones hechas en la vista afectan a ese array, en cambio, La **copia** duplica los datos del array y las modificaciones hechas en la copia no afectan al array original