<a href="https://colab.research.google.com/github/iecgerman/python-numpy-pandas/blob/master/clase09.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# Caso Práctico de Análisis de Datos

In [58]:
# VER UN COMENTARIO EN EL PASO 6 PORQUE LO COMENTE TODO

"""import numpy as np

months = np.array(["Enero","Febrero","Marzo", "Abril", "Mayo", "Junio","Julio", "Agosto", "Septiembre", "Octubre", "Noviembre", "Diciembre"])
print(months)

pantalones = np.random.randint(100, 999, size=(1,12))
print(pantalones)

camisas = np.random.randint(100, 999, size=(1,12))
print(camisas)

zapatos = np.random.randint(100, 999, size=(1,12))
print(zapatos)"""

months = np.array(["Enero","Febrero","Marzo", "Abril", "Mayo", "Junio","Julio", "Agosto", "Septiembre", "Octubre", "Noviembre", "Diciembre"])
print(months)

pantalones = np.array([150, 200, 250, 300, 220, 210, 180, 190, 230, 240, 280, 300])
print(pantalones)

camisas = np.array([180, 210, 230, 250, 270, 260, 240, 250, 270, 290, 310, 330])
print(camisas)

zapatos = np.array([200, 220, 240, 260, 280, 300, 320, 340, 360, 380, 400, 420])
print(zapatos)

['Enero' 'Febrero' 'Marzo' 'Abril' 'Mayo' 'Junio' 'Julio' 'Agosto'
 'Septiembre' 'Octubre' 'Noviembre' 'Diciembre']
[150 200 250 300 220 210 180 190 230 240 280 300]
[180 210 230 250 270 260 240 250 270 290 310 330]
[200 220 240 260 280 300 320 340 360 380 400 420]


In [ ]:
# Paso 1: Crear arrays con datos de ventas mensuales

print(pantalones)
print(camisas)
print(zapatos)

suma = pantalones + camisas + zapatos
print("VENTAS POR MES", suma)

[150 200 250 300 220 210 180 190 230 240 280 300]
[180 210 230 250 270 260 240 250 270 290 310 330]
[200 220 240 260 280 300 320 340 360 380 400 420]
VENTAS POR MES [ 530  630  720  810  770  770  740  780  860  910  990 1050]


In [ ]:
# Paso 2: Transformaciones básicas con NumPy
# Estadísticas básicas

# PRECIO PROMEDIO POR PRODUCTOS

media_pantalon = np.mean(pantalones)
print("PRECIO PROMEDIO POR PANTALON:", "{:.2f}".format(media_pantalon))

media_camisa = np.mean(camisas)
print("PRECIO PROMEDIO POR CAMISA:", "{:.2f}".format(media_camisa))

media_zapato = np.mean(zapatos)
print("PRECIO PROMEDIO POR ZAPATOS", "{:.2f}".format(media_zapato))

# VENTA TOTAL POR AÑO DE CADA PRODUCTO

suma_pantalones = np.sum(pantalones)
print("TOTAL DE VENTAS EN TODO EL AÑO DE LOS PANTALONES:", suma_pantalones)

suma_camisas = np.sum(camisas)
print("TOTAL DE VENTAS EN TODO EL AÑO DE LAS CAMISAS:", suma_camisas)

suma_zapatos = np.sum(zapatos)
print("TOTAL DE VENTAS EN TODO EL AÑO DE LOS ZAPATOS:", suma_zapatos)


PRECIO PROMEDIO POR PANTALON: 229.17
PRECIO PROMEDIO POR CAMISA: 257.50
PRECIO PROMEDIO POR ZAPATOS 310.00
TOTAL DE VENTAS EN TODO EL AÑO DE LOS PANTALONES: 2750
TOTAL DE VENTAS EN TODO EL AÑO DE LAS CAMISAS: 3090
TOTAL DE VENTAS EN TODO EL AÑO DE LOS ZAPATOS: 3720


In [ ]:
# Paso 3: Manipulación y análisis de datos
# Calcular el total de ventas por mes

total_ventas_por_mes = pantalones + camisas + zapatos # igual que el paso 1
print("TOTAL DE VENTAS POR MES:",total_ventas_por_mes)

# Calcular el promedio de ventas por producto
promedio_ventas_productos = np.array([media_pantalon, media_camisa, media_zapato])
print("PROMEDIO DE VENTAS DE PANTALONES |  CAMISAS | ZAPATOS <---", promedio_ventas_productos) # no pude darle format de 2 deciamales :(

# Identificar el mes con mayor y menor ventas
mes_mayor_ventas = months[np.argmax(total_ventas_por_mes)]
print("MES CON MAYOR VENTAS: ", {mes_mayor_ventas})

mes_menor_ventas = months[np.argmin(total_ventas_por_mes)]
print("MES CON MENOR VENTAS: ", {mes_menor_ventas})

TOTAL DE VENTAS POR MES: [ 530  630  720  810  770  770  740  780  860  910  990 1050]
PROMEDIO DE VENTAS DE PANTALONES |  CAMISAS | ZAPATOS <--- [229.16666667 257.5        310.        ]
MES CON MAYOR VENTAS:  {'Diciembre'}
MES CON MENOR VENTAS:  {'Enero'}


In [ ]:
# Paso 4: Operaciones avanzadas con NumPy

# Reshape y Transposición

import numpy as np

ventas_matrix = np.array([pantalones, camisas, zapatos])
print("ventas_matrix:\n",ventas_matrix)

ventas_reshaped = ventas_matrix.reshape(3,4,3) # matrices, filas, columnas y todo debe ser divisible entre 12 en este caso, se puede por ejemplo 6,3,2 o 6,2,3
print("\nventas_reshaped en 3 matrix, 4 filas y 3 columnas:\n", ventas_reshaped)

ventas_transposed = ventas_matrix.T # Aquí en este caso se verá linfo invertida, las columnas seran pantalones, camisas y zapatos y cada fila sera un mes
print("\nventas_transposed:\n", ventas_transposed)

# Invertir arrays y aplanar matrices

print("\nventas_matrix:\n",ventas_matrix)

ventas_inverted = ventas_matrix[:, ::-1]
print("\nVENTAS INVERTIDAS:\n", ventas_inverted)

pantalones_inverted = pantalones[::-1]
print("\n...........PRECIOS DE PANTALONES", pantalones)
print("PRECIOS DE PANTALONES INVERTIDOS", pantalones_inverted)

ventas_flattened = ventas_matrix.flatten()
print("\nVENTAS APLANADAS: \n", ventas_flattened)


ventas_matrix:
 [[150 200 250 300 220 210 180 190 230 240 280 300]
 [180 210 230 250 270 260 240 250 270 290 310 330]
 [200 220 240 260 280 300 320 340 360 380 400 420]]

ventas_reshaped en 3 matrix, 4 filas y 3 columnas:
 [[[150 200 250]
  [300 220 210]
  [180 190 230]
  [240 280 300]]

 [[180 210 230]
  [250 270 260]
  [240 250 270]
  [290 310 330]]

 [[200 220 240]
  [260 280 300]
  [320 340 360]
  [380 400 420]]]

ventas_transposed:
 [[150 180 200]
 [200 210 220]
 [250 230 240]
 [300 250 260]
 [220 270 280]
 [210 260 300]
 [180 240 320]
 [190 250 340]
 [230 270 360]
 [240 290 380]
 [280 310 400]
 [300 330 420]]

ventas_matrix:
 [[150 200 250 300 220 210 180 190 230 240 280 300]
 [180 210 230 250 270 260 240 250 270 290 310 330]
 [200 220 240 260 280 300 320 340 360 380 400 420]]

VENTAS INVERTIDAS:
 [[300 280 240 230 190 180 210 220 300 250 200 150]
 [330 310 290 270 250 240 260 270 250 230 210 180]
 [420 400 380 360 340 320 300 280 260 240 220 200]]

...........PRECIOS DE PANTALON

In [ ]:
# Paso 5: Análisis de elementos únicos y sus conteos

unique_ventas, count_ventas = np.unique(ventas_flattened, return_counts=True)
print("Elementos unicos en las ventas aplanadas:\n", unique_ventas)
print("Conteos de los elementos unicos en las ventas aplanadas:\n", count_ventas)

Elementos unicos en las ventas aplanadas:
 [169 203 212 261 276 284 316 331 374 382 436 447 462 502 536 541 552 561
 564 599 639 707 718 745 769 801 814 915 926 938 947 964 970 976 992 998]
Conteos de los elementos unicos en las ventas aplanadas:
 [1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]


In [68]:
# Paso 6: Indexación y slicing

# Seleccionar ventas del primer trimestre

ventas_primer_trimestre = ventas_matrix[:, :3]
print("VENTAS:\n",ventas_matrix)
print("\nventas del primer trimestre:\n", ventas_primer_trimestre)

# Indexación booleana para seleccionar meses con ventas totales superiores a 800

meses_altas_ventas = months[total_ventas_por_mes > 800]
print("\nMeses que vendieron arriba de $800 pesos:\n", meses_altas_ventas)

ventas_mayor_800 = total_ventas_por_mes[total_ventas_por_mes > 800]
print("\nFiltro de ventas arriba de $800 pesos:\n", ventas_mayor_800)

index_meses = [0,1,2,11]
ventas_index_meses = ventas_matrix[:, index_meses]
print("\nVentas de meses \n Ene | Feb | Mar | Dic \n", ventas_index_meses)

VENTAS:
 [[150 200 250 300 220 210 180 190 230 240 280 300]
 [180 210 230 250 270 260 240 250 270 290 310 330]
 [200 220 240 260 280 300 320 340 360 380 400 420]]

ventas del primer trimestre:
 [[150 200 250]
 [180 210 230]
 [200 220 240]]

Meses que vendieron arriba de $800 pesos:
 ['Abril' 'Septiembre' 'Octubre' 'Noviembre' 'Diciembre']

Filtro de ventas arriba de $800 pesos:
 [ 810  860  910  990 1050]

Ventas de meses 
 Ene | Feb | Mar | Dic 
 [[150 200 250 300]
 [180 210 230 330]
 [200 220 240 420]]
