<a href="https://colab.research.google.com/github/iecgerman/python-numpy-pandas/blob/master/clase05.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# Indexación y Slicing

In [2]:
import numpy as np

array = np.array([10,20,30,40,50])
print(array[1])
print(array[-1])

20
50


In [3]:
print(array[1:4])

[20 30 40]


In [4]:
print(array[1:7])

[20 30 40 50]


In [5]:
print(array[-1:-7])

[]


In [10]:
array = np.array([10,20,30,40,50])
bool_index = array > 25
print(bool_index)
print(type(bool_index))

[False False  True  True  True]
<class 'numpy.ndarray'>


In [13]:
index = [2,0,4]
print(array[index])

[30 10 50]


In [20]:
array = np.random.randint(1,10, size=(3,3))
print(array)
print(array[0,1])

[[5 9 3]
 [7 6 2]
 [3 2 3]]
9


In [27]:
print(array[:3,:2])

[[5 9]
 [7 6]
 [3 2]]
