<a href="https://colab.research.google.com/github/iecgerman/python-numpy-pandas/blob/master/clase07.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [34]:
# Elementos Únicos y sus Conteos: Copias y Vistas

import numpy as np

survey_responses = np.array(["bueno", "excelente", "malo",
                             "bueno", "malo", "excelente",
                             "bueno", "bueno", "malo",
                             "excelente", "excelente", "excelente"])

print(np.unique(survey_responses))


['bueno' 'excelente' 'malo']


In [61]:
unique_elements, counts = np.unique(survey_responses, return_counts=True)
print(unique_elements)
print(counts)

print("\nCréditos a Rodolfo Turpo R. - https://platzi.com/comentario/5194168/")
counts_dict = dict(zip(survey_responses,counts))
print(counts_dict)

print("\n quería imprimir algo asi como en este ejemplo https://es.stackoverflow.com/questions/438163/python-imprimir-un-diccionario-en-columnas")
for valor in counts_dict:
  print(f"{valor[0:9]:<15} {valor[0:9]}")
for valor in counts_dict:
  print(f"{valor[0:9]:<15} {counts_dict.values()}")
for clave in counts_dict:
  print(clave)
for valor in counts:
  print(valor)

print("\nhttps://github.com/iecgerman/10002-python/blob/master/clase14.py")
pares = counts_dict.items()
print(pares)

['bueno' 'excelente' 'malo']
[4 5 3]

Créditos a Rodolfo Turpo R. - https://platzi.com/comentario/5194168/
{'bueno': 4, 'excelente': 5, 'malo': 3}

 quería imprimir algo asi como en este ejemplo https://es.stackoverflow.com/questions/438163/python-imprimir-un-diccionario-en-columnas
bueno           bueno
excelente       excelente
malo            malo
bueno           dict_values([4, 5, 3])
excelente       dict_values([4, 5, 3])
malo            dict_values([4, 5, 3])
bueno
excelente
malo
4
5
3

https://github.com/iecgerman/10002-python/blob/master/clase14.py
dict_items([('bueno', 4), ('excelente', 5), ('malo', 3)])


Elementos Únicos y Conteos:

Utiliza **np.unique** para encontrar elementos únicos y sus conteos en arrays unidimensionales y multidimensionales.

In [10]:
# Ejemplo con ejercicio de clase 6 de Broadcasting

prices = np.random.randint(1, 99, size=(10,10))
print(prices)

unique_elements_in_prices, counts = np.unique(prices, return_counts=True)
print(unique_elements_in_prices)
print(counts)

counts_dict_zip = dict(zip(unique_elements_in_prices, counts))
print(counts_dict_zip)

[[80 12 65 13 83 52 64 51 30 57]
 [ 3  1 41 39 38 47 15  9 70 52]
 [82 74 80 81 44 80 65 24 53 89]
 [59 79 57 60 84 64 44 57  1 36]
 [71 60 71 28 74  3 87 90 50 62]
 [35 58  3 67 85 40 58 77 78 33]
 [19 90 42 41 60 78 18 36 56 30]
 [81 74 88 20 61 61 62 94 60 97]
 [65 35 63 58 28  1  3 93 85 62]
 [47 32 87 42 90 56 34 50 35  4]]
[ 1  3  4  9 12 13 15 18 19 20 24 28 30 32 33 34 35 36 38 39 40 41 42 44
 47 50 51 52 53 56 57 58 59 60 61 62 63 64 65 67 70 71 74 77 78 79 80 81
 82 83 84 85 87 88 89 90 93 94 97]
[3 4 1 1 1 1 1 1 1 1 1 2 2 1 1 1 3 2 1 1 1 2 2 2 2 2 1 2 1 2 3 3 1 4 2 3 1
 2 3 1 1 2 3 1 2 1 3 2 1 1 1 2 2 1 1 3 1 1 1]
{1: 3, 3: 4, 4: 1, 9: 1, 12: 1, 13: 1, 15: 1, 18: 1, 19: 1, 20: 1, 24: 1, 28: 2, 30: 2, 32: 1, 33: 1, 34: 1, 35: 3, 36: 2, 38: 1, 39: 1, 40: 1, 41: 2, 42: 2, 44: 2, 47: 2, 50: 2, 51: 1, 52: 2, 53: 1, 56: 2, 57: 3, 58: 3, 59: 1, 60: 4, 61: 2, 62: 3, 63: 1, 64: 2, 65: 3, 67: 1, 70: 1, 71: 2, 74: 3, 77: 1, 78: 2, 79: 1, 80: 3, 81: 2, 82: 1, 83: 1, 84: 1, 85: 2, 87: 2,

In [ ]:
# VISTAS

array_x = np.arange(10)
print(array_x)
view_y = array_x[1:3]
print(view_y)

array_x[1:3] = [10,11]
print(array_x)
print(view_y)

[0 1 2 3 4 5 6 7 8 9]
[1 2]
[ 0 10 11  3  4  5  6  7  8  9]
[10 11]


In [ ]:
# COPIAS

array_x = np.arange(10)
copy_x = array_x[[1,2]]
print(array_x)
print(copy_x)
array_x[1:3] = [10,11]
print(array_x)
print(copy_x)

[0 1 2 3 4 5 6 7 8 9]
[1 2]
[ 0 10 11  3  4  5  6  7  8  9]
[1 2]


Copias y Vistas:

Las **vistas** son referencias al mismo bloque de memoria que el array original, mientras que las **copias** son réplicas independientes. Cambios en una vista afectan al array original, pero cambios en una copia no.

Las **vistas** comparten la memoria con el array original y las modificaciones hechas en la vista afectan a ese array, en cambio, La **copia** duplica los datos del array y las modificaciones hechas en la copia no afectan al array original