<a href="https://colab.research.google.com/github/iecgerman/python-numpy-pandas/blob/master/clase06.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# Broadcasting y Operaciones Lógicas en NumPy

In [5]:
import numpy as np

prices = np.array([100,200,300])
discount = np.array([0.9])

discount_prices = prices * discount
print(discount_prices)

[ 90. 180. 270.]


In [53]:
prices = np.random.randint(100,500, size=(5,3))
discount = np.array([.9,.8,.7])
discount_prices = prices * discount
print(prices)
print(discount_prices)

[[296 153 487]
 [167 178 155]
 [484 296 200]
 [401 453 265]
 [437 499 280]]
[[266.4 122.4 340.9]
 [150.3 142.4 108.5]
 [435.6 236.8 140. ]
 [360.9 362.4 185.5]
 [393.3 399.2 196. ]]


In [20]:
array =  np.array([1,2,3,4,5])
print(np.all(array > 9))

False


In [21]:
print(np.any(array > 4))

True


In [22]:
array_a = np.array([1,2,3])
array_b = np.array([4,5,6])
concatenated = np.concatenate((array_a, array_b))
print(concatenated)

[1 2 3 4 5 6]


In [24]:
stacked_v = np.vstack((array_a, array_b))
print(stacked_v)

[[1 2 3]
 [4 5 6]]


In [25]:
#STACKING

stacked_h = np.hstack((array_a, array_b))
print(stacked_h)

[1 2 3 4 5 6]


In [39]:
#SPLIT

array_c = np.arange(1,16)
split_array = np.split(array_c,3)
print(array_c)
print(split_array)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]
[array([1, 2, 3, 4, 5]), array([ 6,  7,  8,  9, 10]), array([11, 12, 13, 14, 15])]
